name: Init stock data
on: workflow_dispatch
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch data
        run: |
          ls
          bash init.sh
      - name: Commit and push
        run: |
          git config --global user.email "tiet@ehkoo.com"
          git config --global user.name "tiet"
          git add -A
          git commit -m "Init stock data" || exit 0
          git push
